#!/bin/bash
#

set -eo pipefail

export PATH=$PATH:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:.
. <( arv-dax setup )

mntdir=`arv-dax keep`
jobparam=`arv-dax script_parameters`

ifn=$mntdir/`echo "$jobparam" | jq -r '.INPUT_FILE'`

cp -R $CRUNCH_SRC/crunch_scripts/html/* .
cp -R $ifn/out-report.json .

arv-dax task finish
exit 0
